name: CI with AWS CodeBuild

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: codebuild-hmai-org-codebuild-services-runners-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: whoami